# Generated by Django 6.0.5 on 2026-05-18 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "desk_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер стола"
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, verbose_name="Дополнительная информация"
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workplace",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рабочее место",
                "verbose_name_plural": "Рабочие места",
                "ordering": ("desk_number",),
            },
        ),
    ]
